title: Brian's Blog
description: PowerShell, Azure, and other things I break

theme: jekyll-theme-modernist
author:
  name: Brian McCammon

header_image: /header.jpg
plugins:
  - jekyll-feed
  - jekyll-seo-tag
