title: Brian's Blog
description: PowerShell, Azure, and other things I break

theme: jekyll-theme-dinky
author:
  name: Brian McCammon

header_image: /assets/images/header.jpg
plugins:
  - jekyll-feed
  - jekyll-seo-tag
